### ISSUE TITLE
Duda con sintaxis

### ISSUE THREAD

**Issue by MacoChave** [ericknavarro/InterpreteSencilloJisonJS#1]
https://github.com/ericknavarro/InterpreteSencilloJisonJS/blob/master/gramatica.jison#L77
Cuál es la diferencia de [$1] y $1 como en la línea 77?

**Comment by rjanixz** [comment]
Jison está basadon en javascript y se usa el simbolo $$ para la síntesis de valores, de la misma forma que CUP lo hace con la palabra reservada RESULT.

Javascript al ser un lenguaje de tipado débil permite la asignación de diferentes tipos de datos a una variable. En el caso del ejemplo del tutorial, el no terminal `instrucciones` se maneja como un array de objetos `Instruccion`. 

Por lo que cuando reconocemos la primera instrucción retornamos un array con la primer instrucción reconocida. `$1` es la primera instrucción e indicamos que es un arreglo con los simbolos `[` y `]`. Por esa razón retornamos `[$1]`

En las siguientes iteraciones `$1` representa nuestro array que retornamos previamente, hacemos uso de la función `push` propia de los arreglos de javascript para insertar la siguiente instrucción que reconocimos, finalmente retornamos `$1` que, como ya vimos sigue siendo un array.

Te recomiendo revisar la sintaxis de javascript para manejo de arreglos y objetos para que puedas familiarizarte mejor con este tipo de código.

**Comment by MacoChave** [comment]
Gracias por la respuesta.
No ví que era en instrucciones que estaba esa regla, lo siento.
