### ISSUE TITLE
El bucle FOR

### ISSUE THREAD

**Issue by gpeitzner** [ericknavarro/InterpreteSencilloJisonJS#13]
Propongo agregar esta estructura de control básica al interprete. Tendrá la siguiente estructura:

Para(Asignación; Expresión Lógica; Aumento){
     Instrucciones*
}

Ejemplo:

`numero i;
para(i=0; i < 10; i++){
/* Instrucciones */
}`

Saludos.

**Comment by rjanixz** [comment]
Issue resuelto en: https://github.com/ericknavarro/InterpreteSencilloJisonJS/pull/15

@gpeitzner buen trabajo. Mandame un correo con tus datos: carnet, nombre, usuario de github, sección, número de issue, y número de pull request para control de tu nota.
