### ISSUE TITLE
Propuesta de gramática para switch

### ISSUE THREAD

**Issue by CRISLEV** [ericknavarro/InterpreteSencilloJisonJS#19]
Se propone agregar la gramatica para el switch:

```
instruccion -> RSWITCH PARIZQ expresion_numerica PARDER LLAVIZQ casos LLAVDER

casos -> casos caso_evaluar
                | caso_evaluar

caso_evaluar -> RCASE expresion_numerica DOSPTS instrucciones
                              | RDEFAULT DOSPTS instrucciones
```

Se dejaría indicada la sentencia Break para que alguien pueda completar esas acciones.

![image](https://user-images.githubusercontent.com/22825989/74581661-5f7dbd80-4f77-11ea-91f6-734d7881e629.png)

**Comment by ericknavarro** [comment]
Buenas noches @CRISLEV 
Esta buena la propuesta, por favor trabajar en el pull request correspondiente.
Saludos cordiales.

**Comment by rjanixz** [comment]
Muchas gracias por tu aporte @CRISLEV . Ya tomé tus datos para validar tu aporte al curos.

Saludos.
