### ISSUE TITLE
El lenguaje no acepta asignaciones a la hora de declarar variables

### ISSUE THREAD

**Issue by DavidJGG** [ericknavarro/InterpreteSencilloJisonJS#2]
El interprete no cuenta con asignaciones a la hora de declarar una variable 
Ejemplo:

**numero** num1 = 70;  <-- Este tipo de operación actualmente no es aceptada.

Se recomienda extender el lenguaje para que la operación sea aceptada.

**Comment by rjanixz** [comment]
@DavidJGG no olvides también enviar el desarrollo de la mejora propuesta haciendo un respectivo pull request.

**Comment by rjanixz** [comment]
PR https://github.com/ericknavarro/InterpreteSencilloJisonJS/pull/7

**Comment by rjanixz** [comment]
Se cierra issue por falta de respuesta en solicitud de cambios
