### ISSUE TITLE
Validación de división

### ISSUE THREAD

**Issue by pablorrp1** [ericknavarro/InterpreteSencilloJisonJS#3]
Por el momento el programa puede hacer divisiones de cualquier número, sin embargo al hacer una división entre 0 (Ejemplo: 10/0) el resultado es "Infinito".
Podría crearse una excepción y reportar como error esas divisiones.

**Comment by rjanixz** [comment]
@pablorrp1 Excelente observación, no olvides que parte de la tarea es proponer la solución en código a través de un pull request. Saludos.

**Comment by rjanixz** [comment]
Issue resuelto en: https://github.com/ericknavarro/InterpreteSencilloJisonJS/pull/18

@pablorrp1 buen trabajo. Mandame un correo con tus datos: carnet, nombre,  usuario de github, sección, número de issue, y número de pull request para control de tu nota.
