### ISSUE TITLE
Boolean

### ISSUE THREAD

**Issue by jj196** [ericknavarro/InterpreteSencilloJisonJS#5]
Agregar tipo de dato Boolean, para  poder hacer comparaciones con true o false en las e expresiones lógicas

**Comment by rjanixz** [comment]
@jj196  recuerda hacer tu propuesta de solución desarrollado el código y abrir el respectivo pull request. Podes tomar en cuenta la propuesta del tipo de dato String propuesto por uno de tus compañeros,

**Comment by ericknavarro** [comment]
Se cierra el issue por falta de actividad.
