### ISSUE TITLE
Operadores Relacionales y Lógicos

### ISSUE THREAD

**Issue by DuglasAT** [ericknavarro/InterpreteSencilloJisonJS#6]
Actualmente el intérprete solamente soporta los operadores relacionales '>' y '<' y no soporta operadores lógicos 'AND', 'OR', 'NOT'.
Se propone agregar los operadores relacionales '>=', '<=', '==', '!=' y los operadores lógicos '&&' (AND), '||' (OR), '!' (NOT).

**Comment by rjanixz** [comment]
@DuglasAT  recuerda hacer tu propuesta de solución desarrollado el código y abrir el respectivo pull request.

**Comment by rjanixz** [comment]
Issue resuelto en https://github.com/ericknavarro/InterpreteSencilloJisonJS/pull/16

@DuglasAT buen trabajo. Mandame un correo con tus datos: carnet, nombre, usuario de github, sección, número de issue, y número de pull request para control de tu nota.
