### ISSUE TITLE
Operadores de asignación

### ISSUE THREAD

**Issue by AlisonLeiva** [ericknavarro/InterpreteSencilloJisonJS#8]
El proyecto no acepta asignaciones donde  se juntan los operadores con el de asignación.

Por ejemplo:
**numero = numero + 10;**   
Puede simplificarse a:
**numero += 10;**

**Comment by AlexizzArevalo** [comment]
:) excelente idea!

**Comment by rjanixz** [comment]
@AlisonLeiva recuerda hacer tu propuesta de solución desarrollado el código y abrir el respectivo pull request.

**Comment by ericknavarro** [comment]
Muchas gracias por tu trabajo Alison, por favor seguir al pendiente hasta que el pull request se haya aprobado y hecho merge con el master: https://github.com/ericknavarro/InterpreteSencilloJisonJS/pull/17

Saludos cordiales.

**Comment by rjanixz** [comment]
Muchas gracias por tu aporte @AlisonLeiva , por favor enviarme un correo con la siguiente información:

carnet, nombre, usuario de github, sección, repositorio, número de issue y número de pull request.
