### ISSUE TITLE
Definir valor por defecto para las variables de tipo numero.

### ISSUE THREAD

**Issue by bernaldrpp** [ericknavarro/InterpreteSencilloJisonJS#9]
Al intentar imprimir el valor por defecto de una variable recien creada, sin haberle sido asignado ningun valor el interprete no logra compilar el codigo ingresado.
Ejemplos:
Entrada:
      numero num;
      imprimir("Valor por defecto de num: " & num);
Salida de Consola:
     return procesarExpresionNumerica(expresion, tablaDeSimbolos).toString()
     TypeError: Cannot read property 'toString' of undefined

**Comment by bernaldrpp** [comment]
Ejemplo 2:
Entrada:

numero num;
num = num+1;
imprimir("Valor de num: " & num);

Salida

Valor de num: NaN

**Comment by rjanixz** [comment]
@bernaldrpp la propuesta es buena, pero se debe considerar otros tipos de datos, reivsa los pr para que podas tomar en cuenta los otros tipos de datos propuestos

**Comment by ericknavarro** [comment]
Se cierra el issue por falta de actividad.
Saludos cordiales.
